[package]
name = "rust-to-cpp"
version = "0.1.0"
authors = ["y-sugino <ysgn0101@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
